### ISSUE TITLE
Mood Tracking and Journaling

### ISSUE THREAD

**Issue by rahma-abdelwahab** [nourrosama/MindMatters#35]
- [ ] Build mood logging functionality.

- [ ] Enable journaling feature.

- [ ] Add edit and view functionality for past entries.
